### ISSUE TITLE
Expense Reporting Dashboards - PP3 

### ISSUE THREAD

**Issue by JoseAnaya28** [status-im/insights-bi#10]
@sashayar13 
- [x] Expense Reporting Dashboard for dev.app
- [x] Expense Reporting Dashboard for test.app
- [x] Expense Reporting Dashboard for prod

**Comment by JoseAnaya28** [comment]
- [x] Created schemas for each spiff environment:

stg_dev_spiff
stg_test_spiff
stg_prod_spiff

- [x] Created expense and expense item models for each environment:

expenses
expense_items

https://github.com/status-im/dbt-models/commit/96a9c53d65a517a3f1afa4d882ca9d153f7c8574

**Comment by JoseAnaya28** [comment]
@sashayar13 

dev dashboard:
https://superset.bi.status.im/superset/dashboard/39/

test.app:
https://superset.bi.status.im/superset/dashboard/46/

**Comment by JoseAnaya28** [comment]
prod dashboard:
https://superset.bi.status.im/superset/dashboard/47/
